# Generated by Django 5.0.3 on 2026-02-16 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('protocol', models.CharField(db_index=True, help_text='Número de protocolo único gerado automaticamente', max_length=50, unique=True, verbose_name='Protocolo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('waiting_triage', 'Aguardando Triagem'), ('in_analysis', 'Em Análise'), ('forwarded', 'Encaminhada'), ('resolved', 'Resolvida'), ('closed', 'Encerrada')], default='waiting_triage', max_length=20, verbose_name='Status')),
                ('origin', models.CharField(choices=[('app', 'Aplicativo Mobile'), ('web', 'Portal Web'), ('whatsapp', 'WhatsApp'), ('phone', 'Telefone')], default='web', max_length=20, verbose_name='Origem')),
                ('location_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Endereço')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Anônimo')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestations', to=settings.AUTH_USER_MODEL, verbose_name='Cidadão')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestations_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
            ],
            options={
                'verbose_name': 'Manifestação',
                'verbose_name_plural': 'Manifestações',
                'db_table': 'manifestations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Arquivo')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.manifestation', verbose_name='Manifestação')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('sla_hours', models.PositiveIntegerField(default=72, help_text='Tempo máximo em horas para resolução', verbose_name='SLA (horas)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.manifestationcategory', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria de Manifestação',
                'verbose_name_plural': 'Categorias de Manifestação',
                'db_table': 'manifestation_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestations', to='reports.manifestationcategory', verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='ManifestationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('internal_note', models.TextField(blank=True, help_text='Nota visível apenas para a equipe interna', null=True, verbose_name='Nota Interna')),
                ('public_note', models.TextField(blank=True, help_text='Nota visível ao cidadão', null=True, verbose_name='Nota Pública')),
                ('new_status', models.CharField(choices=[('waiting_triage', 'Aguardando Triagem'), ('in_analysis', 'Em Análise'), ('forwarded', 'Encaminhada'), ('resolved', 'Resolvida'), ('closed', 'Encerrada')], max_length=20, verbose_name='Novo Status')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='reports.manifestation', verbose_name='Manifestação')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestation_updates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Andamento',
                'verbose_name_plural': 'Andamentos',
                'db_table': 'manifestation_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='manifestation',
            index=models.Index(fields=['protocol'], name='manifestati_protoco_aaab3f_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestation',
            index=models.Index(fields=['status'], name='manifestati_status_d43b81_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestation',
            index=models.Index(fields=['created_at'], name='manifestati_created_8f9385_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestation',
            index=models.Index(fields=['latitude', 'longitude'], name='manifestati_latitud_aca045_idx'),
        ),
    ]
