# Generated by Django 5.0.3 on 2026-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='citizen_correction',
            field=models.TextField(blank=True, help_text='Observação adicional do cidadão caso discorde da análise da IA', null=True, verbose_name='Correção do Cidadão'),
        ),
    ]
