# Generated by Django 5.0.3 on 2026-02-16 17:17

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_manifestation_citizen_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição opcional do anexo (ex: "Foto do buraco")', max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'Imagem'), ('DOCUMENT', 'Documento'), ('AUDIO', 'Áudio'), ('VIDEO', 'Vídeo'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo de Arquivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='manifestations/%Y/%m/%d/', validators=[reports.models.validate_file_upload], verbose_name='Arquivo'),
        ),
    ]
