# Generated by Django 5.0.3 on 2026-02-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_workorder_and_manifestation_work_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_sector_92fbce_idx',
            old_name='work_orders_sector_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_status_3f6c76_idx',
            old_name='work_orders_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_schedul_a0bdce_idx',
            old_name='work_orders_scheduled_idx',
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='True se esta manifestação é a representante do grupo (pai)', verbose_name='É Primária'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='potential_duplicate',
            field=models.ForeignKey(blank=True, help_text='ID da manifestação próxima sugerida pelo algoritmo de deduplicação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potential_duplicates_of', to='reports.manifestation', verbose_name='Possível Duplicata De'),
        ),
        migrations.AlterField(
            model_name='manifestation',
            name='related_group',
            field=models.ForeignKey(blank=True, help_text='Manifestação "pai" quando esta é agrupada a outra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_manifestations', to='reports.manifestation', verbose_name='Grupo Relacionado (Pai)'),
        ),
    ]
