# Generated by Django 5.0.3 on 2026-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_manifestation_embedding_add_column_if_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestation',
            name='status',
            field=models.CharField(choices=[('waiting_triage', 'Aguardando Triagem'), ('in_analysis', 'Em Análise'), ('forwarded', 'Encaminhada'), ('duplicate_forwarded', 'Duplicata Encaminhada'), ('resolved', 'Resolvida'), ('closed', 'Encerrada')], default='waiting_triage', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manifestationupdate',
            name='new_status',
            field=models.CharField(choices=[('waiting_triage', 'Aguardando Triagem'), ('in_analysis', 'Em Análise'), ('forwarded', 'Encaminhada'), ('duplicate_forwarded', 'Duplicata Encaminhada'), ('resolved', 'Resolvida'), ('closed', 'Encerrada')], max_length=20, verbose_name='Novo Status'),
        ),
    ]
