# Generated by Django 5.0.3 on 2026-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_manifestation_embedding_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='service_data',
            field=models.JSONField(blank=True, help_text='Armazena dados flexíveis de formulários específicos (ex: dados do animal para castração, agenda, etc.)', null=True, verbose_name='Dados Específicos do Serviço'),
        ),
        migrations.AddField(
            model_name='manifestationcategory',
            name='is_smart_service',
            field=models.BooleanField(default=False, help_text='Se True, aciona fluxos específicos no frontend (ex: formulário de castração)', verbose_name='É Serviço Inteligente?'),
        ),
    ]
