# Generated by Django 5.0.3 on 2026-03-06 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_add_service_data_and_is_smart_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Clínica/Parceiro')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('accepted_types', models.JSONField(blank=True, default=list, help_text='Ex: ["Cão Macho", "Cão Fêmea", "Gato Macho", "Gato Fêmea"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parceiro de Serviço',
                'verbose_name_plural': 'Parceiros de Serviço',
                'db_table': 'service_partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do Atendimento')),
                ('time_slot', models.CharField(max_length=50, verbose_name='Horário/Período (Ex: 08:00 - 12:00)')),
                ('total_slots', models.IntegerField(default=10, verbose_name='Vagas Totais')),
                ('booked_slots', models.IntegerField(default=0, verbose_name='Vagas Ocupadas')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.servicepartner')),
            ],
            options={
                'verbose_name': 'Agenda de Serviço',
                'verbose_name_plural': 'Agendas de Serviço',
                'db_table': 'service_schedules',
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='manifestation',
            name='service_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestations', to='reports.serviceschedule', verbose_name='Agendamento Vinculado'),
        ),
    ]
