# Generated by Django 5.0.3 on 2026-02-16 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLPAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Valor entre -1.0 (muito negativo) e +1.0 (muito positivo)', verbose_name='Score de Sentimento')),
                ('urgency_level', models.IntegerField(default=3, help_text='Valor de 1 (baixa) a 5 (crítica) calculado pela IA', verbose_name='Nível de Urgência')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Lista de palavras-chave extraídas pela IA', verbose_name='Palavras-chave')),
                ('summary', models.TextField(blank=True, help_text='Resumo gerado pela IA para leitura rápida do gestor', null=True, verbose_name='Resumo')),
                ('raw_ai_response', models.JSONField(blank=True, default=dict, help_text='JSON completo retornado pela API de IA para auditoria futura', verbose_name='Resposta Bruta da IA')),
                ('ai_model_used', models.CharField(blank=True, help_text='Ex: gpt-4, gpt-3.5-turbo, etc.', max_length=100, null=True, verbose_name='Modelo de IA Utilizado')),
                ('analysis_version', models.CharField(default='1.0', help_text='Versão do algoritmo/pipeline de análise usado', max_length=20, verbose_name='Versão da Análise')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Análise')),
                ('manifestation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_analysis', to='reports.manifestation', verbose_name='Manifestação')),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nlp_suggestions', to='reports.manifestationcategory', verbose_name='Categoria Sugerida')),
            ],
            options={
                'verbose_name': 'Análise NLP',
                'verbose_name_plural': 'Análises NLP',
                'db_table': 'nlp_analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['sentiment_score'], name='nlp_analyse_sentime_6c9ce6_idx'), models.Index(fields=['urgency_level'], name='nlp_analyse_urgency_2d9ab4_idx'), models.Index(fields=['analyzed_at'], name='nlp_analyse_analyze_d7e850_idx')],
            },
        ),
    ]
