# Generated by Django 5.0.3 on 2026-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlpanalysis',
            name='intent',
            field=models.CharField(choices=[('COMPLAINT', 'Reclamação'), ('SUGGESTION', 'Sugestão'), ('INFORMATION', 'Dúvida/Informação'), ('DENUNCIATION', 'Denúncia')], default='COMPLAINT', help_text='Tipo de manifestação detectada pela IA', max_length=20, verbose_name='Intenção'),
        ),
    ]
