# Generated by Django 5.0.3 on 2026-03-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_alter_nlpanalysis_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlpanalysis',
            name='intent',
            field=models.CharField(choices=[('COMPLAINT', 'Reclamação'), ('SUGGESTION', 'Sugestão'), ('INFORMATION', 'Dúvida/Informação'), ('DENUNCIATION', 'Denúncia'), ('SERVICE_CASTRATION', 'Serviço - Castração')], default='COMPLAINT', help_text='Tipo de manifestação detectada pela IA', max_length=50, verbose_name='Intenção'),
        ),
    ]
