# Generated by Django 5.0.3 on 2026-02-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_embedding_nullable_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, choices=[('OBRAS', 'OBRAS'), ('SAUDE', 'SAÚDE'), ('ZELADORIA', 'ZELADORIA'), ('TRANSPORTE', 'TRANSPORTE'), ('EDUCACAO', 'EDUCAÇÃO'), ('SEGURANCA', 'SEGURANÇA'), ('MEIO_AMBIENTE', 'MEIO AMBIENTE'), ('ILUMINACAO', 'ILUMINAÇÃO')], help_text='Setor de trabalho do usuário (para controle de acesso no Board de Execução)', max_length=50, null=True, verbose_name='Setor'),
        ),
    ]
